[sudo: authenticate] Password: 



sudo: Authentication failed, try again.
[sudo: authenticate] Password: 
sudo: Authentication failed, try again.
[sudo: authenticate] Password: 
sudo: maximum 3 incorrect authentication attempts
